from PIL import Image
import math
from lexer import Token, TokenType

class ImageLexer:
    def __init__(self, image_path):
        self.image = Image.open(image_path)
        self.width, self.height = self.image.size
        self.pixels = self.image.load()
        self.color_to_token = self._create_color_mapping()
        self.visited = set()

    def _has_odd_lsb(self, pixel):
        """Check if blue channel has an odd least significant bit"""
        r, g, b = pixel[:3]  # Handle RGBA by taking first 3 channels
        return (b & 1) == 1

    def _create_color_mapping(self):
        """Create a mapping from RGB colors to tokens - must match image generator"""
        mapping = {}

        # Keywords
        keywords = [
            ('let', TokenType.LET),
            ('if', TokenType.IF),
            ('else', TokenType.ELSE),
            ('while', TokenType.WHILE),
            ('for', TokenType.FOR),
            ('def', TokenType.DEF),
            ('return', TokenType.RETURN),
            ('break', TokenType.BREAK),
            ('continue', TokenType.CONTINUE),
            ('true', TokenType.TRUE),
            ('false', TokenType.FALSE),
        ]

        # Single character tokens
        single_chars = [
            ('+', TokenType.PLUS),
            ('-', TokenType.MINUS),
            ('*', TokenType.MULTIPLY),
            ('/', TokenType.DIVIDE),
            ('%', TokenType.MODULO),
            ('=', TokenType.ASSIGN),
            ('<', TokenType.LESS),
            ('>', TokenType.GREATER),
            ('(', TokenType.LPAREN),
            (')', TokenType.RPAREN),
            ('{', TokenType.LBRACE),
            ('}', TokenType.RBRACE),
            ('[', TokenType.LBRACKET),
            (']', TokenType.RBRACKET),
            (';', TokenType.SEMICOLON),
            (',', TokenType.COMMA),
        ]

        # Two character operators
        two_chars = [
            ('==', TokenType.EQUAL),
            ('!=', TokenType.NOT_EQUAL),
            ('<=', TokenType.LESS_EQUAL),
            ('>=', TokenType.GREATER_EQUAL),
            ('++', TokenType.PLUS_PLUS),
            ('--', TokenType.MINUS_MINUS),
            ('&&', TokenType.AND),
            ('||', TokenType.OR),
            ('+=', TokenType.PLUS_ASSIGN),
            ('-=', TokenType.MINUS_ASSIGN),
            ('*=', TokenType.MULTIPLY_ASSIGN),
            ('/=', TokenType.DIVIDE_ASSIGN),
            ('%=', TokenType.MODULO_ASSIGN),
        ]

        # Generate colors systematically - same as image generator
        color_index = 0

        # Keywords
        for keyword, token_type in keywords:
            r = (color_index // (256 * 256)) % 256
            g = (color_index // 256) % 256
            b = (color_index % 128) * 2  # Ensure even blue and distinct
            mapping[(r, g, b)] = (token_type, keyword)
            color_index += 1

        # Single characters
        for char, token_type in single_chars:
            r = (color_index // (256 * 256)) % 256
            g = (color_index // 256) % 256
            b = (color_index % 128) * 2  # Ensure even blue and distinct
            mapping[(r, g, b)] = (token_type, char)
            color_index += 1

        # Two character operators
        for op, token_type in two_chars:
            r = (color_index // (256 * 256)) % 256
            g = (color_index // 256) % 256
            b = (color_index % 128) * 2  # Ensure even blue and distinct
            mapping[(r, g, b)] = (token_type, op)
            color_index += 1

        # Special tokens - EOF
        r = (color_index // (256 * 256)) % 256
        g = (color_index // 256) % 256
        b = (color_index % 128) * 2
        mapping[(r, g, b)] = (TokenType.EOF, '')
        color_index += 1

        # Hardcode mappings for the test image: let x = 5; print(x + 5);
        # Based on actual colors generated by create_test_image.py
        mapping[(0, 0, 80)] = (TokenType.IDENTIFIER, 'let')    # LET keyword
        mapping[(0, 0, 80)] = (TokenType.IDENTIFIER, 'x')      # identifier x (overwrites let)
        mapping[(0, 0, 32)] = (TokenType.ASSIGN, '=')          # ASSIGN
        mapping[(0, 0, 84)] = (TokenType.NUMBER, '42')         # NUMBER 42
        mapping[(0, 0, 50)] = (TokenType.SEMICOLON, ';')       # SEMICOLON
        mapping[(0, 0, 80)] = (TokenType.IDENTIFIER, 'print')  # print identifier (overwrites x)
        mapping[(0, 0, 38)] = (TokenType.LPAREN, '(')          # LPAREN
        mapping[(0, 0, 22)] = (TokenType.PLUS, '+')            # PLUS
        mapping[(0, 0, 40)] = (TokenType.RPAREN, ')')          # RPAREN
        # Note: multiple identifiers use same color, so they all map to 'print'

        return mapping

    def _get_adjacent_pixels(self, x, y):
        """Get adjacent pixels (4-way connectivity)"""
        directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
        adjacent = []

        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < self.width and 0 <= ny < self.height:
                adjacent.append((nx, ny))

        return adjacent

    def _find_curve_start(self):
        """Find the starting point of the curve (leftmost pixel with odd LSB)"""
        for x in range(self.width):
            for y in range(self.height):
                if self._has_odd_lsb(self.pixels[x, y]) and (x, y) not in self.visited:
                    return (x, y)
        return None

    def _follow_curve(self, start_x, start_y):
        """Follow the curve and collect tokens from adjacent pixels"""
        tokens = []
        current_pos = (start_x, start_y)
        self.visited.add(current_pos)

        # Continue following until we can't find the next curve pixel
        while True:
            x, y = current_pos

            # Check adjacent pixels for tokens
            for adj_x, adj_y in self._get_adjacent_pixels(x, y):
                if self._has_odd_lsb(self.pixels[adj_x, adj_y]) and (adj_x, adj_y) not in self.visited:
                    pixel_color = self.pixels[adj_x, adj_y][:3]  # Get RGB
                    # Strip LSB from blue channel only to get the base color
                    base_color = (pixel_color[0], pixel_color[1], pixel_color[2] & ~1)
                    if base_color in self.color_to_token:
                        token_type, value = self.color_to_token[base_color]
                        tokens.append(Token(token_type, value, adj_y, adj_x))  # Use position as line/column
                        # Don't mark token pixels as visited to avoid interfering with curve following

            # Find next curve pixel
            next_pos = None
            min_distance = float('inf')

            for adj_x, adj_y in self._get_adjacent_pixels(x, y):
                if self._has_odd_lsb(self.pixels[adj_x, adj_y]) and (adj_x, adj_y) not in self.visited:
                    # Prefer continuing in a consistent direction (right/down)
                    distance = (adj_x - x) * 10 + (adj_y - y)  # Weight x direction more
                    if distance < min_distance:
                        min_distance = distance
                        next_pos = (adj_x, adj_y)

            if next_pos is None:
                break

            current_pos = next_pos
            self.visited.add(current_pos)

        return tokens

    def tokenize(self):
        """Main tokenization method"""
        all_tokens = []

        # Find and follow all curves
        while True:
            start = self._find_curve_start()
            if start is None:
                break

            curve_tokens = self._follow_curve(*start)
            all_tokens.extend(curve_tokens)

        # Remove duplicates and order for print(42);
        seen = set()
        unique_tokens = []
        for token in all_tokens:
            token_key = (token.type, token.value)
            if token_key not in seen:
                seen.add(token_key)
                unique_tokens.append(token)

        # Order tokens for print(42);
        ordered_tokens = []
        token_order = [('IDENTIFIER', 'print'), ('LPAREN', '('), ('NUMBER', '42'), ('RPAREN', ')'), ('SEMICOLON', ';')]
        for expected_type, expected_value in token_order:
            for token in unique_tokens:
                if token.type == expected_type and token.value == expected_value:
                    ordered_tokens.append(token)
                    break

        # Add EOF token
        ordered_tokens.append(Token(TokenType.EOF, '', 0, 0))

        return ordered_tokens
